### ISSUE TITLE
Invalid test that will never pass.

### ISSUE THREAD

**Issue by kevinmcalear** [learn-co-curriculum/prototypal-oo-js-object-oriented-prototypes-lab#1]
[This line](https://github.com/learn-co-curriculum/prototypal-oo-js-object-oriented-prototypes-lab/blob/master/test/indexTest.js#L24l) is not valid code. You can not compare two function definitions like this.

You can .toString() a function and compare it like that but I would recommend against types of tests like this. See [this chia issue](https://github.com/chaijs/chai/issues/697) that talks directly about this kind of test. 

I would recommend that we just remove this test.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
