### ISSUE TITLE
Prototypes are not mentioned in any prior labs- Curriculum Issues

### ISSUE THREAD

**Issue by ScottDenton** [learn-co-curriculum/prototypal-oo-js-object-oriented-prototypes-lab#2]
This lab is the first time there has been any mention of prototypes in the JavaScript Curriculum. 
There is an explanation of how JavaScript has a prototypal inheritance modal but no where does it actually mention using Prototypes within a function/class. 

I think there needs to be some mention of how to set a prototype prior to the lab or within the readme for this lab. Something simple explaining the difference between the two functions below would be sufficient.

```
this.sayHi = function(){
    return `Hi, my name is ${this.name}. I am from ${this.homeState}, and I was trained in ${this.training}.`
  }

 'Class'.prototype.sayHi = function(){
    return `Hi, my name is ${this.name}. I am from ${this.homeState}, and I was trained in ${this.training}.`
  }


```

**Comment by sgharms** [comment]
This seems reasonable. We'll find a way to integrate this idea.

**Comment by maxwellbenton** [comment]
Hi @ScottDenton,

Thank you for spotting this and providing feedback. We've reordered the content in this section, removed a duplicate lesson and added in a lesson that had not been added and believe this issue has been resolved.

Thank you for participating in testing this curriculum content and for helping to improve it for future students! 💙
